# Generated by Django 6.0.7 on 2026-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_alerts',
            field=models.BooleanField(default=True, verbose_name='Alertes de la résidence'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_incidents',
            field=models.BooleanField(default=True, verbose_name='Incidents (nouveaux et suivis)'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_replies',
            field=models.BooleanField(default=True, verbose_name='Réponses à mes messages'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_by_email',
            field=models.BooleanField(default=True, verbose_name='Recevoir des emails'),
        ),
    ]
