# Generated by Django 6.0.7 on 2026-08-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_notify_alerts_user_notify_incidents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencemodule',
            name='module',
            field=models.CharField(choices=[('incidents', "Centre d'incidents"), ('wall', "Mur d'actualité"), ('directory', 'Carnet de santé')], max_length=30),
        ),
    ]
