# Generated by Django 6.0.7 on 2026-08-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_conseil_syndical_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Résidence de démonstration'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='Compte de démonstration'),
        ),
    ]
