# Generated by Django 6.0.7 on 2026-08-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_residence_user_is_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRequestCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name="Clé d'endpoint")),
                ('ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('last_at', models.DateTimeField(verbose_name='Dernier passage')),
            ],
            options={
                'verbose_name': 'Limitation de débit (endpoint public)',
                'verbose_name_plural': 'Limitations de débit (endpoints publics)',
                'unique_together': {('key', 'ip')},
            },
        ),
    ]
