# Generated by Django 6.0.7 on 2026-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publicrequestcooldown'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifiedError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=32, unique=True, verbose_name='Signature')),
                ('last_notified_at', models.DateTimeField(verbose_name='Dernière notification')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Occurrences')),
            ],
            options={
                'verbose_name': 'Erreur 500 notifiée',
                'verbose_name_plural': 'Erreurs 500 notifiées',
            },
        ),
    ]
