# Generated by Django 6.0.7 on 2026-08-11 21:44

import wall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_postphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='image',
            field=models.ImageField(upload_to=wall.models.post_photo_upload),
        ),
    ]
