# Generated by Django 6.0.7 on 2026-08-26 21:58

import core.validators
import wall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_photo_uuid_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='image',
            field=models.ImageField(upload_to=wall.models.post_photo_upload, validators=[core.validators.validate_photo]),
        ),
    ]
