# Generated by Django 6.0.7 on 2026-08-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
