# Generated by Django 6.0.7 on 2026-08-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_incidentcategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcategory',
            name='icon',
            field=models.CharField(default='wrench', max_length=32, verbose_name='Icône (nom Lucide, ex. wrench)'),
        ),
    ]
