# Generated by Django 6.0.7 on 2026-08-11 21:44

import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_seed_lucide_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentphoto',
            name='image',
            field=models.ImageField(upload_to=incidents.models.incident_photo_upload),
        ),
    ]
