# Generated by Django 6.0.7 on 2026-08-26 21:58

import core.validators
import incidents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_photo_uuid_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentphoto',
            name='image',
            field=models.ImageField(upload_to=incidents.models.incident_photo_upload, validators=[core.validators.validate_photo]),
        ),
    ]
