# Generated by Django 6.0.7 on 2026-08-03 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('urgence', 'Urgences'), ('conseil', 'Conseil syndical'), ('syndic', 'Syndic'), ('entreprise', 'Entreprises')], max_length=20, verbose_name='Catégorie')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Rôle / spécialité')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.residence')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('date', models.DateField(verbose_name='Date')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='Entreprise')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant (€)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.residence')),
            ],
            options={
                'verbose_name': 'Travaux',
                'ordering': ['-date'],
            },
        ),
    ]
