# Generated by Django 6.0.7 on 2026-08-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_notify_alerts_user_notify_incidents_and_more'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='core.residence')),
            ],
            options={
                'verbose_name': 'Info pratique',
                'verbose_name_plural': 'Infos pratiques',
                'ordering': ['order', 'title'],
            },
        ),
    ]
